version: '3.8'

services:
  order-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    environment:
      - NODE_ENV=production
      - DB_PATH=/data/orders.db
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=mlkj123+
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  data: